txnDir;					// M 交易方向       
storeId;				// M 特店代號       
endpointCode;			// M 端末代號       
terminalId;				// M 終端號         
orderNumber;			// M 訂單編號       
txnType;				// M 交易類型       
txnSeqno;				// M 銀行端交易序號 
txnStatus;				// M 訂單交易狀態   
payType;				// M 付款方式       
acctDate;				// C 帳務日期       
txnAccNO;				// M 付款人帳號/卡號
crtDate;				// M 建立日期       
crtTime;				// M 建立時間       
txnDate;				// C 端末交易日期   
txnTime;				// C 端末交易時間   
txnCurrency;			// M 交易幣別碼     
txnAmt;					// M 訂單金額       
carrierType;			// C 載具類別代碼   
carrierId1;				// C 載具顯碼 id    
storeMemo;				// M 店家端保留欄   
rtnCode;				// M 執行結果代碼   
rtnMsg;					// M 執行結果說明   
sign;					// M 簽章           