txnDir;					// N  M 交易方向       
storeId;				// N  M 特店代號       
endpointCode;			// N  M 端末代號       
terminalId;				// N  M 終端號         
orderNumber;			// Y  M 訂單編號       
txnType;				// Y  M 交易類型       
txnSeqno;				// Y  M 銀行端交易序號 
txnStatus;				// Y  M 訂單交易狀態   
payType;				// Y  M 付款方式       
acctDate;				// N  C 帳務日期       
txnAccNO;				// Y  M 付款人帳號/卡號
crtDate;				// Y? M 建立日期       
crtTime;				// Y? M 建立時間       
txnDate;				// Y  C 端末交易日期   
txnTime;				// Y  C 端末交易時間   
txnCurrency;			// Y  M 交易幣別碼     
txnAmt;					// Y  M 訂單金額       
carrierType;			// N  C 載具類別代碼   
carrierId1;				// Y  C 載具顯碼 id    
storeMemo;				// N  M 店家端保留欄   
rtnCode;				// N  M 執行結果代碼   
rtnMsg;					// Y  M 執行結果說明   
sign;					// ?  M 簽章           